name: fetch_sub

on:
  push:
    paths:
      - 'fetch_sub.py'
      - '.github/workflows/fetch_sub.yml'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install requests
      - run: sudo timedatectl set-timezone Asia/Shanghai

      - name: 执行脚本
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: python fetch_sub.py

      - name: 提交
        run: |
          git config --local user.email "bot@github.com"
          git config --local user.name "API-Harvester"
          git add results/subscriptions.txt results/nodes_raw.txt
          if ! git diff --cached --quiet; then
            git commit -m "Update: $(date +'%Y-%m-%d %H:%M:%S')"
            git push
          fi
